force-app/main/default/objects/DebugLog__c/DebugLog__c.object-meta.xml
<CustomObject>
    <description>Holds debug information</description>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>DL-{00000000}</displayFormat>
        <label>DebugLog #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DebugLog__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <description>The bulk of the log info is dumped into here</description>
    <inlineHelpText>The bulk of the log info is dumped into here</inlineHelpText>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrgAdminSettings__c/OrgAdminSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org Admin Settings</label>
</CustomObject>

force-app/main/default/objects/OrgAdminSettings__c/fields/DebugOn__c.field-meta.xml
<CustomField>
    <fullName>DebugOn__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Turn on debugging</description>
    <inlineHelpText>Turn on debugging</inlineHelpText>
    <label>Debug On</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgAdminSettings__c/fields/TurnAllTriggersOff__c.field-meta.xml
<CustomField>
    <fullName>TurnAllTriggersOff__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will turn off ALL triggers and will supercede Trigger Switch settings</description>
    <inlineHelpText>This will turn off ALL triggers and will supercede Trigger Switch settings</inlineHelpText>
    <label>Turn All Triggers Off</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Switch__c/Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Each custom setting record is for a Salesforce Object (Custom or Standard). Enter the API name for the object, and selected whether it&#39;s enabled or not.</description>
    <label>Trigger Switch</label>
</CustomObject>

force-app/main/default/classes/TriggerFactory_TEST.cls
@isTest
public class TriggerFactory_TEST {

	public static testmethod void happyPath() {
		insert new OrgAdminSettings__c(SetupOwnerId = UserInfo.getOrganizationId(),DebugOn__c = true);
		TestHelper th = new TestHelper();
		th.createAdminUser();
		System.runAs(th.Admin) {
			Test.startTest();
			DebugLog__c dbl = new DebugLog__c(Log__c = 'This is a test');
			insert dbl;
			update dbl;
			delete dbl;
			undelete dbl;
			Test.stopTest();
		}
	}

	public static testmethod void triggersOff() {
		insert new OrgAdminSettings__c(SetupOwnerId = UserInfo.getOrganizationId(),TurnAllTriggersOff__c = true,DebugOn__c = true);
		TestHelper th = new TestHelper();
		th.createAdminUser();
		System.runAs(th.Admin) {
			Test.startTest();
			DebugLog__c dbl = new DebugLog__c(Log__c = 'This is a test');
			insert dbl;
			update dbl;
			delete dbl;
			undelete dbl;
			Test.stopTest();
		}
	}

	public static testmethod void objectOff() {
		insert new OrgAdminSettings__c(SetupOwnerId = UserInfo.getOrganizationId(),DebugOn__c = true);
		insert new Trigger_Switch__c(Name = 'DebugLog__c',Enabled__c = false);
		TestHelper th = new TestHelper();
		th.createAdminUser();
		System.runAs(th.Admin) {
			Test.startTest();
			DebugLog__c dbl = new DebugLog__c(Log__c = 'This is a test');
			insert dbl;
			update dbl;
			delete dbl;
			undelete dbl;
			Test.stopTest();
		}
	}

	public static testmethod void fringeCases() {
		insert new OrgAdminSettings__c(SetupOwnerId = UserInfo.getOrganizationId(),DebugOn__c = true);
		insert new Trigger_Switch__c(Name = 'DebugLog__c',Enabled__c = false);
		TestHelper th = new TestHelper();
		th.createAdminUser();
		System.runAs(th.Admin) {
			Test.startTest();
			TriggerFactory.switchForTest = true;
			TriggerFactory.convertObjectNameToHandlerName('a'.repeat(41));
			TriggerFactory.switchForTest = false;
			TriggerFactory.convertObjectNameToHandlerName(null);
			TriggerFactory.initialize(ApexClass.SObjectType);
			Test.stopTest();
		}
	}
}