force-app/main/default/objects/Case/fields/Case_Owner__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created for Compliance and should only show users that are inside of the Compliance roles.</description>
    <label>Case Owner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please enter Compliance team member. If user entered is on the Compliance Team, please contact your administrator</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Cook County Health Compliance Team, Cook County Health Compliance Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Compliance_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Case_Number__c</fullName>
    <description>For Compliance historical data.</description>
    <label>Compliance Case Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Compliance</description>
    <label>Contact Name N</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>Contact_Information__c</fullName>
    <description>Holds historic contact information</description>
    <label>Contact Information (External)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Initiator__c.field-meta.xml
<CustomField>
    <fullName>Initiator__c</fullName>
    <defaultValue>$User.FirstName+ &quot; &quot;+$User.LastName</defaultValue>
    <description>Compliance. meant to grab user at the start of a case and never be changed</description>
    <label>Initiator</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Counter__c/Counter__c.object-meta.xml
<CustomObject>
    <description>Object used to keep track of global counters</description>
    <label>Counter</label>
    <nameField>
        <label>Counter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Counter__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Count</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Is_Union__c.field-meta.xml
<CustomField>
    <fullName>Is_Union__c</fullName>
    <formula>NOT( ISBLANK( UnionID__c ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Union</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Union_Representative__c.field-meta.xml
<CustomField>
    <fullName>Union_Representative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Union Representative</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ComplianceCaseController.cls
public class ComplianceCaseController  {
   
    private final Case c;

    public User CurrentUser {get{
        if(CurrentUser == null) 
            CurrentUser = queryCurrentUser();
            
        return CurrentUser;
    }set;}
    
    public void updateContact() {
        if(c.Contact__c == null) {
            return;
        }
    
        User u = [SELECT Id, Email, Phone
        FROM   User
        WHERE   Id =: c.Contact__c];
        
        if(u != null) {
            c.Contact_Information__c = u.Email;
            
            if(u.Phone != null)
                 c.Contact_Information__c += ', ' + u.Phone;
        }
    }
    
    public ComplianceCaseController(ApexPages.StandardController stdController) {
        this.c = (Case)stdController.getRecord();
        this.c.RecordTypeId = '0121Q000000oFtlQAE';
        
        if(c.id == null && CurrentUser != null) {
            c.Case_Owner__c = CurrentUser.Id;
        }
    }
    
    public void incrementAndAddCounter() {
        Counter__c counter;
        Counter__c[] counters = [SELECT   Id, Count__c
            FROM   Counter__c
            WHERE   Name = 'ComplianceCaseNumber'];
          
        if (counters.size() > 0) 
        {
            counter = counters[0];
          
            Integer count = Integer.ValueOf(counter.Count__c) + 1;
            String countStr = count + '';
            
            if(count <= 9999)
                countStr = '00' + countStr;
            else if(count <= 99999)
                countStr = '0' + countStr;
            else if(count <= 999999)
                countStr = countStr;
                
            c.Compliance_Case_Number__c = countStr;
            
            counter.Count__c = count + '';
            update counter;
        }
    }
    
    public PageReference save() {
        c.OwnerId = c.Case_Owner__c;
        
        try {
            if(c.id == null) {
                if(CurrentUser != null) {
                    c.Initiator__c = CurrentUser.Name;
                }
                
                insert c;
                incrementAndAddCounter();
                update c;
            } else {
                update c;
            }
            
            if(c.id != null) {
                PageReference casePage = new PageReference('/lightning/r/Case/' + c.id + '/view');
                //PageReference casePage = new ApexPages.StandardController(c).view();
                casePage.setRedirect(true);
                return casePage;
            }
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
            
        
        return null;
    }
    
    private User queryCurrentUser() {
        return [
            SELECT   Id, Email, Name, Profile.Name, UserRole.DeveloperName, Union_Representative__c, Is_Union__c 
            FROM   User 
            WHERE   Id =: UserInfo.getUserId()
        ];
    }
}