force-app/main/default/objects/Case/fields/ContactName__c.field-meta.xml
<CustomField>
    <fullName>ContactName__c</fullName>
    <formula>Contact.FirstName + &#39; &#39; + Contact.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/EPO__c.field-meta.xml
<CustomField>
    <fullName>EPO__c</fullName>
    <label>EPO#</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/EPO_Complainant_Non_Employee__c.field-meta.xml
<CustomField>
    <fullName>EPO_Complainant_Non_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Complainant Non-Employee</label>
    <referenceTo>NonEmployee__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/EPO_Complaint_Employee__c.field-meta.xml
<CustomField>
    <fullName>EPO_Complaint_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Complainant Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Grievance.recordType-meta.xml
<RecordType>
    <fullName>Grievance</fullName>
    <active>true</active>
    <businessProcess>Grievances</businessProcess>
    <description>Select if Grievance</description>
    <label>Grievance</label>
</RecordType>

force-app/main/default/objects/NonEmployee__c/NonEmployee__c.object-meta.xml
<CustomObject>
    <label>NonEmployee</label>
    <nameField>
        <label>Non Employees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NonEmployees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/JobCodeDescription__c.field-meta.xml
<CustomField>
    <fullName>JobCodeDescription__c</fullName>
    <label>Job Code Description</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateCaseSubject.cls
public without sharing class UpdateCaseSubject {
    
    public UpdateCaseSubject(List<Case> cases ) {
        for (Case c : cases) {
            if (c.RecordTypeName__c == 'Grievance')
                c.Subject = c.ContactName__c + ' - ' + c.Status;
            else if (c.RecordTypeName__c == 'EPO Incident') {
              
                  Map<Id, User> usersMap = new Map<Id, User>([Select Id,
                                                            Name,
                                                            JobCodeDescription__c 
                                                            From User
                                                            Where Id = :c.EPO_Complaint_Employee__c]);
         
                  Map<Id, NonEmployee__c> nonEmpMap = new Map<Id, NonEmployee__c>([Select Id,
                                                            Name
                                                            From NonEmployee__c
                                                            Where Id = :c.EPO_Complainant_Non_Employee__c]);
                
                c.Subject = '';
                if ( usersMap.get(c.EPO_Complaint_Employee__c) != null )
                    c.Subject = c.EPO__c + ' ' + usersMap.get(c.EPO_Complaint_Employee__c).Name;
                else if ( nonEmpMap.get(c.EPO_Complainant_Non_Employee__c) != null )
                    c.Subject = c.EPO__c + ' ' + nonEmpMap.get(c.EPO_Complainant_Non_Employee__c).Name; 
                else c.Subject = c.EPO__c + ' ' + 'No Complainant Info';
            }
        }    
    }
    
}