force-app/main/default/objects/Case/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Compliance</description>
    <label>Contact Name N</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Counter__c/Counter__c.object-meta.xml
<CustomObject>
    <description>Object used to keep track of global counters</description>
    <label>Counter</label>
    <nameField>
        <label>Counter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Counter__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Count</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ComplianceCaseController_TEST.cls
@isTest
private class ComplianceCaseController_TEST {
    
    static testMethod void simpleTest() {
    User u = [SELECT Id FROM User WHERE UserName = 'pundareekam.kudikala@cookcountyhhs.org'];
    Case testCase = new Case();
    
        System.runAs(u){
            testCase.Contact__c = u.Id;
            ApexPages.StandardController sc = new ApexPages.StandardController(testCase);
            ComplianceCaseController ccc = new ComplianceCaseController(sc);
            PageReference ref = new PageReference('/apex/NewComplianceCaseForm');
            test.setCurrentPage(ref);
            ccc.save();
            User u1 = new User();
            u1 = ccc.CurrentUser;
            ccc.updateContact(); 
            testCase.Contact__c = null;
            ccc.updateContact();   
            
            
            Counter__C counter = new Counter__c();
            counter.Count__c = '0';
            counter.Name = 'ComplianceCaseNumber';
            insert counter;
            
            ccc.incrementAndAddCounter();
            counter.Count__c = '10000';
            update counter;
            ccc.incrementAndAddCounter();
        }
 
  }
}