force-app/main/default/objects/Case/fields/EPO_Complaint_Employee__c.field-meta.xml
<CustomField>
    <fullName>EPO_Complaint_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Complainant Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/EPO_Date_Entered__c.field-meta.xml
<CustomField>
    <fullName>EPO_Date_Entered__c</fullName>
    <label>EPO Receive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Step_1_Comments__c.field-meta.xml
<CustomField>
    <fullName>Step_1_Comments__c</fullName>
    <description>Comments for Step 1</description>
    <label>Step 1 Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Grievance.recordType-meta.xml
<RecordType>
    <fullName>Grievance</fullName>
    <active>true</active>
    <businessProcess>Grievances</businessProcess>
    <description>Select if Grievance</description>
    <label>Grievance</label>
</RecordType>

force-app/main/default/objects/OrgAdminSettings__c/OrgAdminSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org Admin Settings</label>
</CustomObject>

force-app/main/default/objects/User/fields/UnionDescription__c.field-meta.xml
<CustomField>
    <fullName>UnionDescription__c</fullName>
    <label>Union Description</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/UnionID__c.field-meta.xml
<CustomField>
    <fullName>UnionID__c</fullName>
    <label>Union ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Case_TH_TEST.cls
@isTest
private class Case_TH_TEST {
    
    @isTest static void simpleTest() {
        
        insert new OrgAdminSettings__c();
        TestHelper th = new TestHelper();
        
        th.UserProfileNames = new List<String>{'Cook County Health Employee','Cook County Health Standard User'};
            
            th.createAdminUser(false);
        th.createUserRecords(false);
        
        
        
        th.Admin.UnionID__c = 'a';
        th.Admin.UnionDescription__c = 'abc';
        
        for(User u:th.UserRecords) {
            u.ManagerId = th.Admin.Id;
            u.UnionID__c = th.Admin.UnionID__c;
            u.UnionDescription__c = th.Admin.UnionDescription__c;
        }
        
        insert th.UserRecords;
        
        th.Admin.ManagerId = th.UserRecords[0].Id;
        
        insert th.Admin;
        
        
        System.runAs(th.Admin) {
            
            List<Case> cs = new List<Case>();
            
            for(RecordType rt:[SELECT Id FROM RecordType WHERE SObjectType = 'Case' And Name = 'Grievance']) {
                cs.add(new Case(
                    RecordTypeID = rt.Id,
                    Status = 'New'
                ));
            }   
            for(RecordType rt:[SELECT Id FROM RecordType WHERE SObjectType = 'Case' And Name = 'EPO Incident']) {
                cs.add(new Case(
                    RecordTypeID = rt.Id,
                    Status = 'New',
                    EPO_Complaint_Employee__c = th.UserRecords[0].Id,
                    EPO_Date_Entered__c = Date.valueOf('2020-02-29')
                ));
            }
            for(RecordType rt:[SELECT Id FROM RecordType WHERE SObjectType = 'Case' And Name = 'EPO Incident']) {
                cs.add(new Case(
                    RecordTypeID = rt.Id,
                    Status = 'New',
                    EPO_Date_Entered__c = Date.valueOf('2020-02-29')
                ));
            }            
            
            insert cs;
            update cs;
            
            for(Case c:cs) c.Step_1_Comments__c = 'something';
            
            try { update cs; } catch(Exception e) {}
            
            //Case_TH.populateTeamMembersMap();
            Case_TH.populateCaseTeamRoleMap();
            System.debug(Case_TH.getRecordTypeIdToName());
            System.debug(Case_TH.getTeamMembersMap()+'');
            System.debug(Case_TH.getCaseTeamRoleMap());
            System.debug(Case_TH.getCasesAlreadyUpdated());
        }
    }
}