force-app/main/default/objects/Case/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supervisors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/TR_Supervisor_Approval_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>TR_Supervisor_Approval_Date_Time__c</fullName>
    <label>Supervisor Approval Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tuition_Reimbursement_Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Tuition_Reimbursement_Case_Status__c</fullName>
    <label>Supervisor Approval Status</label>
    <picklist>
        <picklistValues>
            <fullName>Approved,</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Rejected,</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Approved - Grades Submitted</fullName>
        </picklistValues>
        <restrictedPicklist>true</restrictedPicklist>
    </picklist>
    <type>Picklist</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <formula>CASESAFEID(User__r.Supervisor__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supervisor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <label>Supervisor User</label>
    <relationshipName>Employee</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/TR_ApprovalSupervisor_Controller.cls
public with sharing class TR_ApprovalSupervisor_Controller {
    
    ApexPages.StandardController stdctrl;
    public boolean showCaseDetails {get; set;}
    public Case currentCase;
    public User owner;
    public User CurrentUser {get{
        if(CurrentUser == null) 
            CurrentUser = queryCurrentUser();
        
        return CurrentUser;
    }set;}
    
    public TR_ApprovalSupervisor_Controller(ApexPages.StandardController stdController) {
        stdctrl = stdController;
        currentCase = (Case) stdController.getRecord();
        if (currentCase.Id != null)
        { 
            currentCase = [Select Id, Supervisor__c, Tuition_Reimbursement_Case_Status__c From Case Where Id = :currentCase.Id];
            if ( currentCase.Supervisor__c == CurrentUser.Id )
            {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,
                                                           '* When reviewing and approving  Tuition Reimbursement Requests there are three elements necessary for compliance.' + '<br/>' +
                                                           '1.Nursing or Nursing related degree documentation' +'<br/>' +
                                                           '2.Official course curriculum for the Semester ' +'<br/>' +
                                                           '3.Course schedule with start and end dates ' +'<br/>' +
                                                           'Please refer below link for Supporting Tools ' 
                                                          ));
                showCaseDetails = true;
            }
            else
            {
                showCaseDetails = false;
                if (currentCase.Tuition_Reimbursement_Case_Status__c == 'Approved' || 
                    currentCase.Tuition_Reimbursement_Case_Status__c == 'Rejected' ||
                    currentCase.Tuition_Reimbursement_Case_Status__c == 'Approved - Grades Submitted')
                    
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'This record is already Approve or Rejected by Supervisor'));
                else
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'This page Can only viewed by supervisor'));          
            }
        }
        else
        {
            showCaseDetails = false;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'No Records Found. Please Contact Your System Administrator'));
        }
    }
    
    public PageReference approve(){
        currentCase.Tuition_Reimbursement_Case_Status__c = 'Approved';
        currentCase.TR_Supervisor_Approval_Date_Time__c = Datetime.now();
        try {
            update currentCase;
            stdctrl.save(); 
        } catch(DmlException e) { 
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'DML Error Occured'));
        }
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Tuition Reimbursement Record Approved.'));  
        return null;       
    }
    
    public PageReference reject(){
        currentCase.Tuition_Reimbursement_Case_Status__c = 'Rejected';
        currentCase.TR_Supervisor_Approval_Date_Time__c = Datetime.now();
        try {
            update currentCase;
            stdctrl.save();
        } catch(DmlException e) { 
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'DML Error Occured'));
        }
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Tuition Reimbursement Record Rejected.'));
        
        return null;
    }
    
    private User queryCurrentUser() {
        return [
            SELECT   Id, Email, Name, Profile.Name, UserRole.DeveloperName, Supervisor__c
            FROM   User 
            WHERE   Id =: UserInfo.getUserId()
        ];
    }
}