force-app/main/default/objects/Field_Mapping__mdt/Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Specifies field mappings for the HR Case Management Portal</description>
    <label>Field Mapping (mine)</label>
    <pluralLabel>Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field_Mapping__mdt/fields/From_Field__c.field-meta.xml
<CustomField>
    <fullName>From_Field__c</fullName>
    <inlineHelpText>Must be the API name for the field</inlineHelpText>
    <label>From Field</label>
    <length>44</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Mapping__mdt/fields/From_Object__c.field-meta.xml
<CustomField>
    <fullName>From_Object__c</fullName>
    <label>From Object</label>
    <picklist>
        <picklistValues>
            <fullName>Case</fullName>
            <default>true</default>
        </picklistValues>
        <picklistValues>
            <fullName>User</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Contact</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Case_Summary__c</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Charge__c</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>EEO_Detail__c</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Witness__c</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Similarly_Treated_Ind__c</fullName>
        </picklistValues>
        <restrictedPicklist>true</restrictedPicklist>
    </picklist>
    <type>Picklist</type>
</CustomField>

force-app/main/default/objects/Field_Mapping__mdt/fields/To_Field__c.field-meta.xml
<CustomField>
    <fullName>To_Field__c</fullName>
    <inlineHelpText>Must be the API name for the field</inlineHelpText>
    <label>To Field</label>
    <length>44</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Mapping__mdt/fields/To_Object__c.field-meta.xml
<CustomField>
    <fullName>To_Object__c</fullName>
    <label>To Object</label>
    <picklist>
        <picklistValues>
            <fullName>Case</fullName>
            <default>true</default>
        </picklistValues>
        <picklistValues>
            <fullName>User</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Contact</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Case_Summary__c</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Charge__c</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>EEO_Detail__c</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Witness__c</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Similarly_Treated_Ind__c</fullName>
        </picklistValues>
        <restrictedPicklist>true</restrictedPicklist>
    </picklist>
    <type>Picklist</type>
</CustomField>

force-app/main/default/classes/MappingProcess.cls
public without sharing class MappingProcess {

	public String ProcessName {get;set;}

	public String FromObject {get;set;}
	public String ToObject {get;set;}
	
	private Set<String> fromPossibles {get;set;}
	private Set<String> toPossibles {get;set;}

	//         FROM,  TO
	public Map<String,String> FieldMappings {get{
		if(FieldMappings == null) FieldMappings = new Map<String,String>();
		return FieldMappings;
	}set;}

	public void addMapping(Field_Mapping__mdt fm) {
		String fixedFromName = MappingUtil.normalizeProcessName(fm.From_Field__c);
		String fixedToName = MappingUtil.normalizeProcessName(fm.To_Field__c);
		if(fromPossibles.contains(fixedFromName) && toPossibles.contains(fixedToName)) {
			FieldMappings.put(fm.From_Field__c,fm.To_Field__c);
		} else {
			System.debug(
				(!fromPossibles.contains(fm.From_Field__c) ? fm.From_Field__c + ' is not a field on ' + FromObject + '\n' : '') +
				(!fromPossibles.contains(fm.To_Field__c) ? fm.To_Field__c + ' is not a field on ' + ToObject : '')
			);
		}
	}

	public MappingProcess(String procName,Field_Mapping__mdt fm) {
		ProcessName = procName;
		fromPossibles = getFieldMap(fm.From_Object__c).keySet();
		toPossibles = getFieldMap(fm.To_Object__c).keySet();
		FromObject = fm.From_Object__c;
		ToObject = fm.To_Object__c;
		addMapping(fm);
	}

	public static Map<String,SObjectField> getFieldMap(String sObjectName) {
		return Schema.getGlobalDescribe().get(sObjectName).getDescribe().fields.getMap();
	}

	public MappingProcess(String x_ProcessName) {
		ProcessName = x_ProcessName;
	}

	public String grabFromBaseQuery() {
		return makeQuery(new Set<String>(FieldMappings.keySet()), FromObject);
	}

	public String grabToBaseQuery() {
		return makeQuery(new Set<String>(FieldMappings.values()), ToObject);
	}

	private String makeQuery(Set<String> fields,String objName) {
		fields.add('Id');
		return 'SELECT ' + String.join(new List<String>(fields), ', ') + ' FROM ' + objName + ' WHERE ';
	}
}