force-app/main/default/objects/DualEmploymentSurvey__c/DualEmploymentSurvey__c.object-meta.xml
<CustomObject>
    <description>This object is used to track employees who have a second job for compliance purposes.</description>
    <label>Dual Employment Survey</label>
    <nameField>
        <label>Dual Employment Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dual Employment Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DualEmploymentSurvey__c/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Current Step</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DualEmploymentSurvey__c/fields/OutsideEmployer1MonEndTime__c.field-meta.xml
<CustomField>
    <fullName>OutsideEmployer1MonEndTime__c</fullName>
    <globalPicklist>X24_Hour_Clock_Values</globalPicklist>
    <label>OutsideEmployer1MonEndTime</label>
    <type>Picklist</type>
</CustomField>

force-app/main/default/objects/DualEmploymentSurvey__c/fields/OutsideEmployer1MonStartTime__c.field-meta.xml
<CustomField>
    <fullName>OutsideEmployer1MonStartTime__c</fullName>
    <globalPicklist>X24_Hour_Clock_Values</globalPicklist>
    <label>OutsideEmployer1MonStartTime</label>
    <type>Picklist</type>
</CustomField>

force-app/main/default/objects/DualEmploymentSurvey__c/fields/OutsideEmployer1TueEndTime__c.field-meta.xml
<CustomField>
    <fullName>OutsideEmployer1TueEndTime__c</fullName>
    <globalPicklist>X24_Hour_Clock_Values</globalPicklist>
    <label>OutsideEmployer1TueEndTime</label>
    <type>Picklist</type>
</CustomField>

force-app/main/default/objects/DualEmploymentSurvey__c/fields/OutsideEmployer1TueStartTime__c.field-meta.xml
<CustomField>
    <fullName>OutsideEmployer1TueStartTime__c</fullName>
    <globalPicklist>X24_Hour_Clock_Values</globalPicklist>
    <label>OutsideEmployer1TueStartTime</label>
    <type>Picklist</type>
</CustomField>

force-app/main/default/classes/DualEmploymentController_TEST.cls
@isTest
private class DualEmploymentController_TEST {
    static testMethod void simpleTest() {
        User u = [SELECT Id FROM User WHERE Alias= 'admin'];
        DualEmploymentSurvey__c survey = new DualEmploymentSurvey__c();
        survey.Current_Step__c = 1;
        
        System.runAs(u){
            DualEmploymentController ccc = new DualEmploymentController();
            ccc.survey = survey;
            
            ccc.save();
            ccc.save();
            if(ccc.CurrentUser != null) System.debug('good');
            if(ccc.getSurvey() != null) System.debug('good');
            if(ccc.survey != null) System.debug('good');
            
            PageReference ref = new PageReference('/apex/DualEmploymentSurvey');
            test.setCurrentPage(ref); 
            ccc.next();
            ccc.previous();
            ccc.previous();
            survey.Current_Step__c = 10;
            ccc.next();
            survey.Current_Step__c = 12;
            ccc.next();
            ccc.calcTotal();
            ccc.calcJob2Hours();
            ccc.calcJob3Hours();
            ccc.calcJob4Hours();
            ccc.startOver();
            survey.OutsideEmployer1MonEndTime__c = '00:00';
            survey.OutsideEmployer1MonStartTime__c = '00:00';
            ccc.calcTotal();
            survey.OutsideEmployer1TueEndTime__c = '00:00';
            survey.OutsideEmployer1TueStartTime__c = '00:00';
            ccc.calcTotal();
            ccc.calcHours(null, null);
            ccc.calcHours('00:00', '00:00');
        }
    }
}