force-app/main/default/objects/User/fields/Is_Union__c.field-meta.xml
<CustomField>
    <fullName>Is_Union__c</fullName>
    <formula>NOT( ISBLANK( UnionID__c ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Union</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Union_Representative__c.field-meta.xml
<CustomField>
    <fullName>Union_Representative__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Union Representative</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FlowLaunch_VFC.cls
public with sharing class FlowLaunch_VFC {

	public static String flowVFPBase = '%_Flow_VFP';

	public List<ApexPage> flowsList {get{
		if(flowsList == null) flowsList = new List<ApexPage>();
		return flowsList;
	}set;}

	public User CurrentUser {get{
		if(CurrentUser == null) CurrentUser = queryCurrentUser();
		return CurrentUser;
	}set;}

	public FlowLaunch_VFC() {
		queryFlowVFPs();
	}

	private User queryCurrentUser() {
		return [
			SELECT 	Id, Profile.Name, UserRole.DeveloperName, Union_Representative__c, Is_Union__c 
			FROM 	User 
			WHERE 	Id =: UserInfo.getUserId()
		];
	}

	public FlowLaunch_VFC queryFlowVFPs() {
		flowsList = [
			SELECT 	Id, Name, MasterLabel, Description
			FROM 	ApexPage 
			WHERE 	Name LIKE:flowVFPBase
			ORDER BY MasterLabel ASC
		];
		return this;
	}
}